---
- name: Disable SWAP since kubernetes can't work with swap enabled
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'