---
    - hosts: all
      become: yes
      gather_facts: yes
      tasks:
        - import_tasks: configure_hosts_ubuntu18.yml
          when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '18'
        - import_tasks: configure_hosts_ubuntu20.yml
          when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '20'
        - import_tasks: disable_swap.yml
        - import_tasks: enable_ipv4_fwd.yml
        - import_tasks: configure_docker_daemon.yml